name: Run Docs Script on Push

on:
  push:
    branches:
      - main # or specify other branches you want to trigger on

jobs:
  run-bash-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install changelog
        run: pip install git-changelog
      - name: Install doxygen
        run: wget -qO- https://www.doxygen.nl/files/doxygen-1.12.0.linux.bin.tar.gz | tar -xz --strip-components=2 -C /usr/local/bin doxygen-1.12.0/bin/

      # Step 2: Run the bash script located in the root of the project
      - name: Run Bash Script
        run: |
          chmod +x ./gendocs.sh  # Make the script executable
          ./gendocs.sh           # Run the script
